apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-proxy-config
  namespace: tcp-proxy
data:
  config.json: |
    {
      "pools": [
        {
          "name": "keydb",
          "local": {
            "port": 6379
          },
          "checks": {
            "commands": [
              {
                "command": "ping\r\n",
                "expect": "+PONG\r\n"
              },
              {
                "command": "set tcp-proxy:test-write 1\r\n",
                "expect": "+OK\r\n"
              }
            ],
            "options": {
              "timeout": 250,
              "interval": 250
            }
          },
          "remote": [
            {
              "id": "keydb-0",
              "host": "keydb-0.keydb.keydb.svc.cluster.local",
              "port": 6379,
              "connectionTimeout": 250
            },
            {
              "id": "keydb-1",
              "host": "keydb-1.keydb.keydb.svc.cluster.local",
              "port": 6379,
              "connectionTimeout": 250
            }
          ]
        }
      ]
    }