apiVersion: v1
kind: Service
metadata:
  name: tcp-proxy
  namespace: test
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
      name: tcp-proxy
  selector:
    app: tcp-proxy